# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_EGH455.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 871)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_Output_Dolphins = QtWidgets.QLabel(self.centralwidget)
        self.label_Output_Dolphins.setText("")
        self.label_Output_Dolphins.setObjectName("label_Output_Dolphins")
        self.gridLayout_4.addWidget(self.label_Output_Dolphins, 4, 1, 1, 1)
        self.label_Surfers = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Surfers.sizePolicy().hasHeightForWidth())
        self.label_Surfers.setSizePolicy(sizePolicy)
        self.label_Surfers.setMinimumSize(QtCore.QSize(0, 30))
        self.label_Surfers.setObjectName("label_Surfers")
        self.gridLayout_4.addWidget(self.label_Surfers, 2, 0, 1, 1)
        self.label_Dolphins = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Dolphins.sizePolicy().hasHeightForWidth())
        self.label_Dolphins.setSizePolicy(sizePolicy)
        self.label_Dolphins.setMinimumSize(QtCore.QSize(0, 30))
        self.label_Dolphins.setObjectName("label_Dolphins")
        self.gridLayout_4.addWidget(self.label_Dolphins, 4, 0, 1, 1)
        self.label_Output_Sharks = QtWidgets.QLabel(self.centralwidget)
        self.label_Output_Sharks.setText("")
        self.label_Output_Sharks.setObjectName("label_Output_Sharks")
        self.gridLayout_4.addWidget(self.label_Output_Sharks, 3, 1, 1, 1)
        self.exportCSVButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportCSVButton.setEnabled(False)
        self.exportCSVButton.setMinimumSize(QtCore.QSize(0, 30))
        self.exportCSVButton.setObjectName("exportCSVButton")
        self.gridLayout_4.addWidget(self.exportCSVButton, 5, 1, 1, 1)
        self.label_Output_Surfers = QtWidgets.QLabel(self.centralwidget)
        self.label_Output_Surfers.setText("")
        self.label_Output_Surfers.setObjectName("label_Output_Surfers")
        self.gridLayout_4.addWidget(self.label_Output_Surfers, 2, 1, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setEnabled(False)
        self.saveButton.setMinimumSize(QtCore.QSize(0, 30))
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_4.addWidget(self.saveButton, 5, 0, 1, 1)
        self.label_stats = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_stats.sizePolicy().hasHeightForWidth())
        self.label_stats.setSizePolicy(sizePolicy)
        self.label_stats.setMinimumSize(QtCore.QSize(0, 30))
        self.label_stats.setObjectName("label_stats")
        self.gridLayout_4.addWidget(self.label_stats, 0, 0, 1, 2)
        self.label_Ouput_Status = QtWidgets.QLabel(self.centralwidget)
        self.label_Ouput_Status.setObjectName("label_Ouput_Status")
        self.gridLayout_4.addWidget(self.label_Ouput_Status, 7, 1, 1, 1)
        self.statsTableView = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsTableView.sizePolicy().hasHeightForWidth())
        self.statsTableView.setSizePolicy(sizePolicy)
        self.statsTableView.setObjectName("statsTableView")
        self.gridLayout_4.addWidget(self.statsTableView, 1, 0, 1, 2)
        self.label_Sharks = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Sharks.sizePolicy().hasHeightForWidth())
        self.label_Sharks.setSizePolicy(sizePolicy)
        self.label_Sharks.setMinimumSize(QtCore.QSize(0, 30))
        self.label_Sharks.setObjectName("label_Sharks")
        self.gridLayout_4.addWidget(self.label_Sharks, 3, 0, 1, 1)
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        self.label_status.setMinimumSize(QtCore.QSize(0, 30))
        self.label_status.setObjectName("label_status")
        self.gridLayout_4.addWidget(self.label_status, 7, 0, 1, 1)
        self.line_bottom = QtWidgets.QFrame(self.centralwidget)
        self.line_bottom.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_bottom.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_bottom.setObjectName("line_bottom")
        self.gridLayout_4.addWidget(self.line_bottom, 6, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_4, 5, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.importCSVButton = QtWidgets.QPushButton(self.centralwidget)
        self.importCSVButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importCSVButton.sizePolicy().hasHeightForWidth())
        self.importCSVButton.setSizePolicy(sizePolicy)
        self.importCSVButton.setMinimumSize(QtCore.QSize(100, 30))
        self.importCSVButton.setObjectName("importCSVButton")
        self.gridLayout_2.addWidget(self.importCSVButton, 0, 1, 1, 1)
        self.label_DLM = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_DLM.sizePolicy().hasHeightForWidth())
        self.label_DLM.setSizePolicy(sizePolicy)
        self.label_DLM.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_DLM.setObjectName("label_DLM")
        self.gridLayout_2.addWidget(self.label_DLM, 3, 0, 1, 1)
        self.csvListWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csvListWidget.sizePolicy().hasHeightForWidth())
        self.csvListWidget.setSizePolicy(sizePolicy)
        self.csvListWidget.setObjectName("csvListWidget")
        self.gridLayout_2.addWidget(self.csvListWidget, 2, 0, 1, 2)
        self.DLMcomboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DLMcomboBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DLMcomboBox.sizePolicy().hasHeightForWidth())
        self.DLMcomboBox.setSizePolicy(sizePolicy)
        self.DLMcomboBox.setMinimumSize(QtCore.QSize(200, 30))
        self.DLMcomboBox.setObjectName("DLMcomboBox")
        self.gridLayout_2.addWidget(self.DLMcomboBox, 3, 1, 1, 1)
        self.videoListWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoListWidget.sizePolicy().hasHeightForWidth())
        self.videoListWidget.setSizePolicy(sizePolicy)
        self.videoListWidget.setObjectName("videoListWidget")
        self.gridLayout_2.addWidget(self.videoListWidget, 1, 0, 1, 2)
        self.loadDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadDataButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadDataButton.sizePolicy().hasHeightForWidth())
        self.loadDataButton.setSizePolicy(sizePolicy)
        self.loadDataButton.setMinimumSize(QtCore.QSize(100, 30))
        self.loadDataButton.setObjectName("loadDataButton")
        self.gridLayout_2.addWidget(self.loadDataButton, 0, 0, 1, 1)
        self.processDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.processDataButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processDataButton.sizePolicy().hasHeightForWidth())
        self.processDataButton.setSizePolicy(sizePolicy)
        self.processDataButton.setMinimumSize(QtCore.QSize(0, 40))
        self.processDataButton.setObjectName("processDataButton")
        self.gridLayout_2.addWidget(self.processDataButton, 4, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 3, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.button_play = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_play.sizePolicy().hasHeightForWidth())
        self.button_play.setSizePolicy(sizePolicy)
        self.button_play.setMinimumSize(QtCore.QSize(20, 0))
        self.button_play.setObjectName("button_play")
        self.gridLayout_5.addWidget(self.button_play, 3, 0, 1, 1)
        self.button_pause = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_pause.sizePolicy().hasHeightForWidth())
        self.button_pause.setSizePolicy(sizePolicy)
        self.button_pause.setMinimumSize(QtCore.QSize(20, 0))
        self.button_pause.setObjectName("button_pause")
        self.gridLayout_5.addWidget(self.button_pause, 3, 1, 1, 1)
        self.button_stop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_stop.sizePolicy().hasHeightForWidth())
        self.button_stop.setSizePolicy(sizePolicy)
        self.button_stop.setMinimumSize(QtCore.QSize(20, 0))
        self.button_stop.setObjectName("button_stop")
        self.gridLayout_5.addWidget(self.button_stop, 3, 2, 1, 1)
        self.label_video_time = QtWidgets.QLabel(self.centralwidget)
        self.label_video_time.setObjectName("label_video_time")
        self.gridLayout_5.addWidget(self.label_video_time, 3, 3, 1, 1)
        self.video_widget_output = QVideoWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_widget_output.sizePolicy().hasHeightForWidth())
        self.video_widget_output.setSizePolicy(sizePolicy)
        self.video_widget_output.setAutoFillBackground(True)
        self.video_widget_output.setObjectName("video_widget_output")
        self.gridLayout_5.addWidget(self.video_widget_output, 1, 0, 1, 4)
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setObjectName("label_output")
        self.gridLayout_5.addWidget(self.label_output, 0, 0, 1, 4)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_5.addWidget(self.horizontalSlider, 2, 0, 1, 4)
        self.gridLayout.addLayout(self.gridLayout_5, 5, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_input = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_input.sizePolicy().hasHeightForWidth())
        self.label_input.setSizePolicy(sizePolicy)
        self.label_input.setObjectName("label_input")
        self.verticalLayout.addWidget(self.label_input)
        self.video_widget_input = QVideoWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_widget_input.sizePolicy().hasHeightForWidth())
        self.video_widget_input.setSizePolicy(sizePolicy)
        self.video_widget_input.setAutoFillBackground(True)
        self.video_widget_input.setObjectName("video_widget_input")
        self.verticalLayout.addWidget(self.video_widget_input)
        self.gridLayout.addLayout(self.verticalLayout, 3, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.videoOnlyDataButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoOnlyDataButton.sizePolicy().hasHeightForWidth())
        self.videoOnlyDataButton.setSizePolicy(sizePolicy)
        self.videoOnlyDataButton.setMinimumSize(QtCore.QSize(100, 30))
        self.videoOnlyDataButton.setObjectName("videoOnlyDataButton")
        self.horizontalLayout.addWidget(self.videoOnlyDataButton)
        self.CSVOnlyDataButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CSVOnlyDataButton.sizePolicy().hasHeightForWidth())
        self.CSVOnlyDataButton.setSizePolicy(sizePolicy)
        self.CSVOnlyDataButton.setMinimumSize(QtCore.QSize(100, 30))
        self.CSVOnlyDataButton.setObjectName("CSVOnlyDataButton")
        self.horizontalLayout.addWidget(self.CSVOnlyDataButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        self.line_middle = QtWidgets.QFrame(self.centralwidget)
        self.line_middle.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_middle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_middle.setObjectName("line_middle")
        self.gridLayout.addWidget(self.line_middle, 4, 0, 1, 3)
        self.line_top = QtWidgets.QFrame(self.centralwidget)
        self.line_top.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_top.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_top.setObjectName("line_top")
        self.gridLayout.addWidget(self.line_top, 2, 0, 1, 3)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EGH455 Wildlife Detection"))
        self.label_Surfers.setText(_translate("MainWindow", "Total Surfers:"))
        self.label_Dolphins.setText(_translate("MainWindow", "Total Dolphins:"))
        self.exportCSVButton.setText(_translate("MainWindow", "Export CSV"))
        self.saveButton.setText(_translate("MainWindow", "Save Video"))
        self.label_stats.setText(_translate("MainWindow", "Statistics "))
        self.label_Ouput_Status.setText(_translate("MainWindow", "TextLabel"))
        self.label_Sharks.setText(_translate("MainWindow", "Total Sharks:"))
        self.label_status.setText(_translate("MainWindow", "Status: "))
        self.importCSVButton.setText(_translate("MainWindow", "Import CSV"))
        self.label_DLM.setText(_translate("MainWindow", "DLM:"))
        self.loadDataButton.setText(_translate("MainWindow", "Load Data"))
        self.processDataButton.setText(_translate("MainWindow", "Process Data "))
        self.button_play.setText(_translate("MainWindow", ">"))
        self.button_pause.setText(_translate("MainWindow", "||"))
        self.button_stop.setText(_translate("MainWindow", "x"))
        self.label_video_time.setText(_translate("MainWindow", "0:0/0:0"))
        self.label_output.setText(_translate("MainWindow", "Player (Output Video) "))
        self.label_input.setText(_translate("MainWindow", "Input Video "))
        self.videoOnlyDataButton.setText(_translate("MainWindow", "Video Analysing"))
        self.CSVOnlyDataButton.setText(_translate("MainWindow", "CSV Analysing"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
