# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_EGH455.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_play = QtWidgets.QPushButton(self.centralwidget)
        self.button_play.setGeometry(QtCore.QRect(260, 670, 41, 20))
        self.button_play.setObjectName("button_play")
        self.button_pause = QtWidgets.QPushButton(self.centralwidget)
        self.button_pause.setGeometry(QtCore.QRect(330, 670, 41, 20))
        self.button_pause.setObjectName("button_pause")
        self.video_widget_input = QVideoWidget(self.centralwidget)
        self.video_widget_input.setGeometry(QtCore.QRect(260, 60, 421, 271))
        self.video_widget_input.setAutoFillBackground(True)
        self.video_widget_input.setObjectName("video_widget_input")
        self.button_stop = QtWidgets.QPushButton(self.centralwidget)
        self.button_stop.setGeometry(QtCore.QRect(400, 670, 41, 20))
        self.button_stop.setObjectName("button_stop")
        self.video_widget_output = QVideoWidget(self.centralwidget)
        self.video_widget_output.setGeometry(QtCore.QRect(260, 370, 421, 271))
        self.video_widget_output.setAutoFillBackground(True)
        self.video_widget_output.setObjectName("video_widget_output")
        self.label_input = QtWidgets.QLabel(self.centralwidget)
        self.label_input.setGeometry(QtCore.QRect(260, 40, 81, 16))
        self.label_input.setObjectName("label_input")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(260, 350, 141, 16))
        self.label_output.setObjectName("label_output")
        self.line_top = QtWidgets.QFrame(self.centralwidget)
        self.line_top.setGeometry(QtCore.QRect(0, 30, 711, 16))
        self.line_top.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_top.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_top.setObjectName("line_top")
        self.line_middle = QtWidgets.QFrame(self.centralwidget)
        self.line_middle.setGeometry(QtCore.QRect(-10, 330, 711, 16))
        self.line_middle.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_middle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_middle.setObjectName("line_middle")
        self.label_stats = QtWidgets.QLabel(self.centralwidget)
        self.label_stats.setGeometry(QtCore.QRect(10, 350, 141, 16))
        self.label_stats.setObjectName("label_stats")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(240, 40, 20, 681))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.processDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.processDataButton.setEnabled(False)
        self.processDataButton.setGeometry(QtCore.QRect(70, 300, 113, 32))
        self.processDataButton.setObjectName("processDataButton")
        self.loadDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadDataButton.setEnabled(False)
        self.loadDataButton.setGeometry(QtCore.QRect(10, 40, 113, 32))
        self.loadDataButton.setObjectName("loadDataButton")
        self.importCSVButton = QtWidgets.QPushButton(self.centralwidget)
        self.importCSVButton.setEnabled(False)
        self.importCSVButton.setGeometry(QtCore.QRect(130, 40, 113, 32))
        self.importCSVButton.setObjectName("importCSVButton")
        self.statsTableView = QtWidgets.QTableView(self.centralwidget)
        self.statsTableView.setGeometry(QtCore.QRect(10, 370, 231, 181))
        self.statsTableView.setObjectName("statsTableView")
        self.videoListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.videoListWidget.setGeometry(QtCore.QRect(10, 70, 231, 91))
        self.videoListWidget.setObjectName("videoListWidget")
        self.label_DLM = QtWidgets.QLabel(self.centralwidget)
        self.label_DLM.setGeometry(QtCore.QRect(20, 270, 41, 31))
        self.label_DLM.setObjectName("label_DLM")
        self.DLMcomboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DLMcomboBox.setEnabled(False)
        self.DLMcomboBox.setGeometry(QtCore.QRect(60, 270, 141, 26))
        self.DLMcomboBox.setObjectName("DLMcomboBox")
        self.label_Surfers = QtWidgets.QLabel(self.centralwidget)
        self.label_Surfers.setGeometry(QtCore.QRect(10, 560, 91, 16))
        self.label_Surfers.setObjectName("label_Surfers")
        self.label_Sharks = QtWidgets.QLabel(self.centralwidget)
        self.label_Sharks.setGeometry(QtCore.QRect(10, 590, 91, 16))
        self.label_Sharks.setObjectName("label_Sharks")
        self.label_Dolphins = QtWidgets.QLabel(self.centralwidget)
        self.label_Dolphins.setGeometry(QtCore.QRect(10, 620, 91, 16))
        self.label_Dolphins.setObjectName("label_Dolphins")
        self.line_bottom = QtWidgets.QFrame(self.centralwidget)
        self.line_bottom.setGeometry(QtCore.QRect(-20, 670, 271, 16))
        self.line_bottom.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_bottom.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_bottom.setObjectName("line_bottom")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setEnabled(False)
        self.saveButton.setGeometry(QtCore.QRect(0, 650, 113, 32))
        self.saveButton.setObjectName("saveButton")
        self.exportCSVButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportCSVButton.setEnabled(False)
        self.exportCSVButton.setGeometry(QtCore.QRect(120, 650, 113, 32))
        self.exportCSVButton.setObjectName("exportCSVButton")
        self.label_Output_Surfers = QtWidgets.QLabel(self.centralwidget)
        self.label_Output_Surfers.setGeometry(QtCore.QRect(100, 560, 60, 16))
        self.label_Output_Surfers.setText("")
        self.label_Output_Surfers.setObjectName("label_Output_Surfers")
        self.label_Output_Sharks = QtWidgets.QLabel(self.centralwidget)
        self.label_Output_Sharks.setGeometry(QtCore.QRect(100, 590, 60, 16))
        self.label_Output_Sharks.setText("")
        self.label_Output_Sharks.setObjectName("label_Output_Sharks")
        self.label_Output_Dolphins = QtWidgets.QLabel(self.centralwidget)
        self.label_Output_Dolphins.setGeometry(QtCore.QRect(110, 620, 60, 16))
        self.label_Output_Dolphins.setText("")
        self.label_Output_Dolphins.setObjectName("label_Output_Dolphins")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(10, 680, 51, 16))
        self.label_status.setObjectName("label_status")
        self.label_Ouput_Status = QtWidgets.QLabel(self.centralwidget)
        self.label_Ouput_Status.setGeometry(QtCore.QRect(60, 680, 611, 16))
        self.label_Ouput_Status.setObjectName("label_Ouput_Status")
        self.Help_toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.Help_toolButton.setGeometry(QtCore.QRect(430, 10, 261, 21))
        self.Help_toolButton.setObjectName("Help_toolButton")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(250, 640, 431, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.csvListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.csvListWidget.setGeometry(QtCore.QRect(10, 170, 231, 91))
        self.csvListWidget.setObjectName("csvListWidget")
        self.videoOnlyDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.videoOnlyDataButton.setGeometry(QtCore.QRect(0, 10, 131, 32))
        self.videoOnlyDataButton.setObjectName("videoOnlyDataButton")
        self.CSVOnlyDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.CSVOnlyDataButton.setGeometry(QtCore.QRect(120, 10, 131, 32))
        self.CSVOnlyDataButton.setObjectName("CSVOnlyDataButton")
        self.label_video_time = QtWidgets.QLabel(self.centralwidget)
        self.label_video_time.setGeometry(QtCore.QRect(480, 670, 161, 16))
        self.label_video_time.setObjectName("label_video_time")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EGH455 Project"))
        self.button_play.setText(_translate("MainWindow", ">"))
        self.button_pause.setText(_translate("MainWindow", "||"))
        self.button_stop.setText(_translate("MainWindow", "x"))
        self.label_input.setText(_translate("MainWindow", "Input Video "))
        self.label_output.setText(_translate("MainWindow", "Player (Output Video) "))
        self.label_stats.setText(_translate("MainWindow", "Statistics "))
        self.processDataButton.setText(_translate("MainWindow", "Process Data "))
        self.loadDataButton.setText(_translate("MainWindow", "Load Data"))
        self.importCSVButton.setText(_translate("MainWindow", "Import CSV"))
        self.label_DLM.setText(_translate("MainWindow", "DLM:"))
        self.label_Surfers.setText(_translate("MainWindow", "Total Surfers:"))
        self.label_Sharks.setText(_translate("MainWindow", "Total Sharks:"))
        self.label_Dolphins.setText(_translate("MainWindow", "Total Dolphins:"))
        self.saveButton.setText(_translate("MainWindow", "Save Video"))
        self.exportCSVButton.setText(_translate("MainWindow", "Export CSV"))
        self.label_status.setText(_translate("MainWindow", "Status: "))
        self.label_Ouput_Status.setText(_translate("MainWindow", "TextLabel"))
        self.Help_toolButton.setText(_translate("MainWindow", "Help"))
        self.videoOnlyDataButton.setText(_translate("MainWindow", "Video Analysing"))
        self.CSVOnlyDataButton.setText(_translate("MainWindow", "CSV Analysing"))
        self.label_video_time.setText(_translate("MainWindow", "0:0/0:0"))

from PyQt5.QtMultimediaWidgets import QVideoWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

