# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HelpWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HelpWindow(object):
    def setupUi(self, HelpWindow):
        HelpWindow.setObjectName("HelpWindow")
        HelpWindow.resize(1116, 632)
        self.centralwidget = QtWidgets.QWidget(HelpWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 100, 381, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 411, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 71, 21))
        self.label_3.setObjectName("label_3")
        self.loadDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadDataButton.setGeometry(QtCore.QRect(70, 160, 113, 32))
        self.loadDataButton.setObjectName("loadDataButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 160, 191, 21))
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(420, 0, 20, 681))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 200, 131, 21))
        self.label_6.setObjectName("label_6")
        self.DLMcomboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DLMcomboBox.setGeometry(QtCore.QRect(140, 200, 141, 26))
        self.DLMcomboBox.setObjectName("DLMcomboBox")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(290, 200, 131, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 220, 241, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 250, 71, 21))
        self.label_9.setObjectName("label_9")
        self.processDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.processDataButton.setGeometry(QtCore.QRect(80, 250, 113, 32))
        self.processDataButton.setObjectName("processDataButton")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(200, 250, 211, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 280, 381, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 310, 421, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 330, 421, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 360, 161, 21))
        self.label_14.setObjectName("label_14")
        self.button_play = QtWidgets.QPushButton(self.centralwidget)
        self.button_play.setGeometry(QtCore.QRect(160, 360, 41, 20))
        self.button_play.setObjectName("button_play")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 390, 161, 21))
        self.label_15.setObjectName("label_15")
        self.button_pause = QtWidgets.QPushButton(self.centralwidget)
        self.button_pause.setGeometry(QtCore.QRect(170, 390, 41, 20))
        self.button_pause.setObjectName("button_pause")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 420, 161, 21))
        self.label_16.setObjectName("label_16")
        self.button_stop = QtWidgets.QPushButton(self.centralwidget)
        self.button_stop.setGeometry(QtCore.QRect(160, 420, 41, 20))
        self.button_stop.setObjectName("button_stop")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(10, 450, 381, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(10, 470, 101, 21))
        self.label_18.setObjectName("label_18")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(110, 470, 261, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(10, 500, 211, 21))
        self.label_19.setObjectName("label_19")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(220, 500, 113, 32))
        self.saveButton.setObjectName("saveButton")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(10, 520, 211, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(340, 500, 81, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(10, 550, 171, 21))
        self.label_22.setObjectName("label_22")
        self.exportCSVButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportCSVButton.setGeometry(QtCore.QRect(190, 550, 113, 32))
        self.exportCSVButton.setObjectName("exportCSVButton")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(310, 550, 101, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(10, 570, 371, 21))
        self.label_24.setObjectName("label_24")
        self.line_middle = QtWidgets.QFrame(self.centralwidget)
        self.line_middle.setGeometry(QtCore.QRect(0, 40, 1141, 16))
        self.line_middle.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_middle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_middle.setObjectName("line_middle")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(450, 10, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(450, 250, 71, 21))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(450, 160, 71, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(450, 100, 381, 21))
        self.label_28.setObjectName("label_28")
        self.saveButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton_2.setGeometry(QtCore.QRect(660, 500, 113, 32))
        self.saveButton_2.setObjectName("saveButton_2")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(640, 250, 211, 21))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(450, 310, 421, 21))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(450, 500, 211, 21))
        self.label_31.setObjectName("label_31")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(550, 470, 261, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.button_play_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_play_2.setGeometry(QtCore.QRect(600, 360, 41, 20))
        self.button_play_2.setObjectName("button_play_2")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(450, 280, 341, 21))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(450, 120, 411, 21))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(630, 160, 191, 21))
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(450, 360, 161, 21))
        self.label_36.setObjectName("label_36")
        self.button_stop_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_stop_2.setGeometry(QtCore.QRect(600, 420, 41, 20))
        self.button_stop_2.setObjectName("button_stop_2")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(450, 450, 381, 21))
        self.label_38.setObjectName("label_38")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(450, 330, 421, 21))
        self.label_40.setObjectName("label_40")
        self.processDataButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.processDataButton_2.setGeometry(QtCore.QRect(520, 250, 113, 32))
        self.processDataButton_2.setObjectName("processDataButton_2")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(450, 520, 211, 21))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(450, 390, 161, 21))
        self.label_42.setObjectName("label_42")
        self.loadDataButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.loadDataButton_2.setGeometry(QtCore.QRect(510, 160, 113, 32))
        self.loadDataButton_2.setObjectName("loadDataButton_2")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(450, 420, 161, 21))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(450, 470, 101, 21))
        self.label_45.setObjectName("label_45")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(780, 500, 211, 21))
        self.label_47.setObjectName("label_47")
        self.button_pause_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_pause_2.setGeometry(QtCore.QRect(610, 390, 41, 20))
        self.button_pause_2.setObjectName("button_pause_2")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(450, 190, 381, 21))
        self.label_35.setObjectName("label_35")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(450, 210, 431, 21))
        self.label_37.setObjectName("label_37")
        self.line_middle_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_middle_2.setGeometry(QtCore.QRect(430, 550, 491, 20))
        self.line_middle_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_middle_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_middle_2.setObjectName("line_middle_2")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(440, 560, 431, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(480, 580, 361, 21))
        self.label_43.setObjectName("label_43")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(10, 60, 331, 21))
        self.label_46.setObjectName("label_46")
        self.videoOnlyDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.videoOnlyDataButton.setGeometry(QtCore.QRect(200, 60, 131, 32))
        self.videoOnlyDataButton.setObjectName("videoOnlyDataButton")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(450, 60, 351, 21))
        self.label_48.setObjectName("label_48")
        self.CSVOnlyDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.CSVOnlyDataButton.setGeometry(QtCore.QRect(680, 60, 131, 32))
        self.CSVOnlyDataButton.setObjectName("CSVOnlyDataButton")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(910, -10, 20, 681))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(950, 10, 431, 21))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(950, 60, 71, 21))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.centralwidget)
        self.label_51.setGeometry(QtCore.QRect(940, 90, 81, 21))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.centralwidget)
        self.label_52.setGeometry(QtCore.QRect(950, 120, 71, 21))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(960, 150, 71, 21))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(940, 180, 71, 21))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(940, 210, 71, 21))
        self.label_55.setObjectName("label_55")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(1010, 60, 20, 531))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_56 = QtWidgets.QLabel(self.centralwidget)
        self.label_56.setGeometry(QtCore.QRect(940, 240, 71, 21))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.centralwidget)
        self.label_57.setGeometry(QtCore.QRect(940, 270, 71, 21))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.centralwidget)
        self.label_58.setGeometry(QtCore.QRect(980, 300, 31, 21))
        self.label_58.setObjectName("label_58")
        self.line_middle_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_middle_3.setGeometry(QtCore.QRect(940, 290, 161, 20))
        self.line_middle_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_middle_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_middle_3.setObjectName("line_middle_3")
        self.line_middle_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_middle_4.setGeometry(QtCore.QRect(940, 320, 161, 20))
        self.line_middle_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_middle_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_middle_4.setObjectName("line_middle_4")
        self.line_middle_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_middle_5.setGeometry(QtCore.QRect(940, 260, 161, 20))
        self.line_middle_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_middle_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_middle_5.setObjectName("line_middle_5")
        self.line_middle_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_middle_6.setGeometry(QtCore.QRect(940, 230, 161, 20))
        self.line_middle_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_middle_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_middle_6.setObjectName("line_middle_6")
        self.line_middle_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_middle_7.setGeometry(QtCore.QRect(940, 200, 161, 20))
        self.line_middle_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_middle_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_middle_7.setObjectName("line_middle_7")
        self.line_middle_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_middle_8.setGeometry(QtCore.QRect(940, 170, 161, 20))
        self.line_middle_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_middle_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_middle_8.setObjectName("line_middle_8")
        self.line_middle_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_middle_9.setGeometry(QtCore.QRect(940, 140, 161, 20))
        self.line_middle_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_middle_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_middle_9.setObjectName("line_middle_9")
        self.line_middle_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_middle_10.setGeometry(QtCore.QRect(940, 110, 161, 20))
        self.line_middle_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_middle_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_middle_10.setObjectName("line_middle_10")
        self.line_middle_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_middle_11.setGeometry(QtCore.QRect(940, 80, 161, 20))
        self.line_middle_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_middle_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_middle_11.setObjectName("line_middle_11")
        self.label_59 = QtWidgets.QLabel(self.centralwidget)
        self.label_59.setGeometry(QtCore.QRect(1030, 60, 71, 21))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.centralwidget)
        self.label_60.setGeometry(QtCore.QRect(1030, 90, 71, 21))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.centralwidget)
        self.label_61.setGeometry(QtCore.QRect(1030, 120, 71, 21))
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.centralwidget)
        self.label_62.setGeometry(QtCore.QRect(1030, 150, 71, 21))
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.centralwidget)
        self.label_63.setGeometry(QtCore.QRect(1030, 180, 71, 21))
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.centralwidget)
        self.label_64.setGeometry(QtCore.QRect(1030, 210, 71, 21))
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.centralwidget)
        self.label_65.setGeometry(QtCore.QRect(1030, 240, 71, 21))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.centralwidget)
        self.label_66.setGeometry(QtCore.QRect(1030, 270, 71, 21))
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.centralwidget)
        self.label_67.setGeometry(QtCore.QRect(1030, 300, 71, 21))
        self.label_67.setObjectName("label_67")
        HelpWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(HelpWindow)
        self.statusbar.setObjectName("statusbar")
        HelpWindow.setStatusBar(self.statusbar)

        self.retranslateUi(HelpWindow)
        QtCore.QMetaObject.connectSlotsByName(HelpWindow)

    def retranslateUi(self, HelpWindow):
        _translate = QtCore.QCoreApplication.translate
        HelpWindow.setWindowTitle(_translate("HelpWindow", "Help"))
        self.label.setText(_translate("HelpWindow", "To get started click the video you would like to analyse. The "))
        self.label_2.setText(_translate("HelpWindow", "container will automatically show videos from the current directory. "))
        self.label_3.setText(_translate("HelpWindow", "Then click"))
        self.loadDataButton.setText(_translate("HelpWindow", "Load Data"))
        self.label_4.setText(_translate("HelpWindow", "to import your selected video."))
        self.label_5.setText(_translate("HelpWindow", "Analysing a New Video"))
        self.label_6.setText(_translate("HelpWindow", "Go to the DLM, click"))
        self.label_7.setText(_translate("HelpWindow", "to choose the deep"))
        self.label_8.setText(_translate("HelpWindow", "learning method you would like."))
        self.label_9.setText(_translate("HelpWindow", "Then click"))
        self.processDataButton.setText(_translate("HelpWindow", "Process Data "))
        self.label_10.setText(_translate("HelpWindow", "to analyse the video with the DLM."))
        self.label_11.setText(_translate("HelpWindow", "Analysing may take a couple minutes please be patient."))
        self.label_12.setText(_translate("HelpWindow", "You can view the statistics of the video inside the statistics container"))
        self.label_13.setText(_translate("HelpWindow", "which is updated automatically with each new frame. "))
        self.label_14.setText(_translate("HelpWindow", "To play the video press"))
        self.button_play.setText(_translate("HelpWindow", ">"))
        self.label_15.setText(_translate("HelpWindow", "To pause the video press"))
        self.button_pause.setText(_translate("HelpWindow", "||"))
        self.label_16.setText(_translate("HelpWindow", "To stop the video press"))
        self.button_stop.setText(_translate("HelpWindow", "x"))
        self.label_17.setText(_translate("HelpWindow", "To adjust your position in the video (fast forward or rewind)"))
        self.label_18.setText(_translate("HelpWindow", "move the slider "))
        self.label_19.setText(_translate("HelpWindow", "To save the analysed video press "))
        self.saveButton.setText(_translate("HelpWindow", "Save Video"))
        self.label_20.setText(_translate("HelpWindow", ".mp4 file in your current directory. "))
        self.label_21.setText(_translate("HelpWindow", "this will put a "))
        self.label_22.setText(_translate("HelpWindow", "To export the CSV file press "))
        self.exportCSVButton.setText(_translate("HelpWindow", "Export CSV"))
        self.label_23.setText(_translate("HelpWindow", "this will export a "))
        self.label_24.setText(_translate("HelpWindow", ".csv file containing the objects referenced in each frame. "))
        self.label_25.setText(_translate("HelpWindow", "Analysing a Video with an Imported CSV"))
        self.label_26.setText(_translate("HelpWindow", "Then click"))
        self.label_27.setText(_translate("HelpWindow", "Then click"))
        self.label_28.setText(_translate("HelpWindow", "To get started click the video you would like to analyse. The "))
        self.saveButton_2.setText(_translate("HelpWindow", "Save Video"))
        self.label_29.setText(_translate("HelpWindow", "to analyse the video with the CSV."))
        self.label_30.setText(_translate("HelpWindow", "You can view the statistics of the video inside the statistics container"))
        self.label_31.setText(_translate("HelpWindow", "To save the analysed video press "))
        self.button_play_2.setText(_translate("HelpWindow", ">"))
        self.label_32.setText(_translate("HelpWindow", "Analysing may take a couple minutes please be patient."))
        self.label_33.setText(_translate("HelpWindow", "container will automatically show videos from the current directory. "))
        self.label_34.setText(_translate("HelpWindow", "to import your selected video."))
        self.label_36.setText(_translate("HelpWindow", "To play the video press"))
        self.button_stop_2.setText(_translate("HelpWindow", "x"))
        self.label_38.setText(_translate("HelpWindow", "To adjust your position in the video (fast forward or rewind)"))
        self.label_40.setText(_translate("HelpWindow", "which is updated automatically with each new frame. "))
        self.processDataButton_2.setText(_translate("HelpWindow", "Process Data "))
        self.label_41.setText(_translate("HelpWindow", ".mp4 file in your current directory. "))
        self.label_42.setText(_translate("HelpWindow", "To pause the video press"))
        self.loadDataButton_2.setText(_translate("HelpWindow", "Load Data"))
        self.label_44.setText(_translate("HelpWindow", "To stop the video press"))
        self.label_45.setText(_translate("HelpWindow", "move the slider "))
        self.label_47.setText(_translate("HelpWindow", "this will put a "))
        self.button_pause_2.setText(_translate("HelpWindow", "||"))
        self.label_35.setText(_translate("HelpWindow", "Click the CSV file relating to the video you have choosen The "))
        self.label_37.setText(_translate("HelpWindow", "container will automatically show CSV files from the current directory"))
        self.label_39.setText(_translate("HelpWindow", "For further information or technical support please contact: "))
        self.label_43.setText(_translate("HelpWindow", "info@connect.qut.edu.au            +61 7 3333 3333"))
        self.label_46.setText(_translate("HelpWindow", "For analysing a new video click "))
        self.videoOnlyDataButton.setText(_translate("HelpWindow", "Video Analysing"))
        self.label_48.setText(_translate("HelpWindow", "For analysing a video with a CSV click "))
        self.CSVOnlyDataButton.setText(_translate("HelpWindow", "CSV Analysing"))
        self.label_49.setText(_translate("HelpWindow", "Shortcuts:"))
        self.label_50.setText(_translate("HelpWindow", "Play video "))
        self.label_51.setText(_translate("HelpWindow", "Pause video "))
        self.label_52.setText(_translate("HelpWindow", "Stop video "))
        self.label_53.setText(_translate("HelpWindow", "Get Help"))
        self.label_54.setText(_translate("HelpWindow", "Load Video"))
        self.label_55.setText(_translate("HelpWindow", "Import CSV"))
        self.label_56.setText(_translate("HelpWindow", "Save Video"))
        self.label_57.setText(_translate("HelpWindow", "Export CSV"))
        self.label_58.setText(_translate("HelpWindow", "Exit"))
        self.label_59.setText(_translate("HelpWindow", "Ctrl+p"))
        self.label_60.setText(_translate("HelpWindow", "Ctrl+o"))
        self.label_61.setText(_translate("HelpWindow", "Ctrl+k"))
        self.label_62.setText(_translate("HelpWindow", "Ctrl+h"))
        self.label_63.setText(_translate("HelpWindow", "Ctrl+l"))
        self.label_64.setText(_translate("HelpWindow", "Ctrl+i"))
        self.label_65.setText(_translate("HelpWindow", "Ctrl+s"))
        self.label_66.setText(_translate("HelpWindow", "Ctrl+e"))
        self.label_67.setText(_translate("HelpWindow", "Ctrl+t"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HelpWindow = QtWidgets.QMainWindow()
    ui = Ui_HelpWindow()
    ui.setupUi(HelpWindow)
    HelpWindow.show()
    sys.exit(app.exec_())

